### PR TITLE
Lazy Streaming Client

### LINKED ISSUE #80: Lazy connection
Are there plans to have a lazy connection support just like https://github.com/friends-of-reactphp/mysql/pull/87 ?

### PR DESCRIPTION
**Pull request by WyriHaximus**
Implements / Closes #80

### CODE REVIEW

**Comment by WyriHaximus** [comment]
@clue yeah working on that, hence the WIP in the title 😋 , was about the commit the `LazyStreamingClient` when I ran into a bug and had to redesign the entire class 🤐 .

**Comment by WyriHaximus** [comment]
@clue this PR is ready for review

**Comment by WyriHaximus** [comment]
@clue cool keep me updated. Do you at some point also want to include a TTL for the connection where it will disconnect after a certain amount of time without activity? (Thinking ahead)

**Comment by WyriHaximus** [comment]
@clue I'll update this PR later today 👍

**Comment by clue** [comment]
@WyriHaximus Just a quick progress update: I've picked this one up earlier this week and have worked out most of the outstanding issues already (including reconnection, idle timeouts and handling pubsub subscriptions). I'll finish this asap because I plan to start using this in a live project no later than next week :shipit:

**Comment by WyriHaximus** [comment]
@clue ok cool, do you still want me to update this or should we close it instead then?

**Comment by clue** [comment]
@WyriHaximus If you feel an update provides any value, I welcome any contribution :+1: Other than that, I'd really want to avoid wasting anybody's work due to duplicate efforts. I'm currently planning to squash your changes to a single commit in a new PR and give proper credit for your initial work :+1:

**Comment by WyriHaximus** [comment]
@clue that works for me 👍

**Comment by clue** [comment]
See #87 :shipit: :tada:

**Comment by WyriHaximus** [comment]
> See #87 :shipit:

Awesome :shipit:

**Pull request closed without merging**
